INFO:__main__:Scraping WBB schedules for year 2002...
INFO:__main__:Scraping WBB schedules for year 2003...
INFO:__main__:Scraping WBB schedules for year 2004...
INFO:__main__:Scraping WBB schedules for year 2005...
INFO:__main__:Scraping WBB schedules for year 2006...
INFO:__main__:Scraping WBB schedules for year 2007...
INFO:__main__:Scraping WBB schedules for year 2008...
INFO:__main__:Scraping WBB schedules for year 2009...
INFO:__main__:Scraping WBB schedules for year 2010...
INFO:__main__:Scraping WBB schedules for year 2011...
INFO:__main__:Scraping WBB schedules for year 2012...
INFO:__main__:Scraping WBB schedules for year 2013...
INFO:__main__:Scraping WBB schedules for year 2014...
INFO:__main__:Scraping WBB schedules for year 2015...
INFO:__main__:Scraping WBB schedules for year 2016...
INFO:__main__:Scraping WBB schedules for year 2017...
INFO:__main__:Scraping WBB schedules for year 2018...
INFO:__main__:Scraping WBB schedules for year 2019...
INFO:__main__:Scraping WBB schedules for year 2020...
INFO:__main__:Scraping WBB schedules for year 2021...
INFO:__main__:Scraping WBB schedules for year 2022...
INFO:__main__:Scraping WBB schedules for year 2023...
INFO:__main__:29.610449862480163 minutes to download 22 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2002...
INFO:__main__:Finished WBB PBP for 2002...
INFO:__main__:Scraping WBB schedules for year 2002...
INFO:__main__:0.7129827221234639 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2002...
INFO:__main__:Finished WBB PBP for 2002...
INFO:__main__:Scraping WBB schedules for year 2003...
INFO:__main__:0.8089955012003581 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2003...
INFO:__main__:Finished WBB PBP for 2003...
INFO:__main__:Scraping WBB schedules for year 2004...
INFO:__main__:0.87280775308609 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2004...
INFO:__main__:Finished WBB PBP for 2004...
INFO:__main__:Scraping WBB schedules for year 2005...
INFO:__main__:0.837358566125234 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2005...
INFO:__main__:Finished WBB PBP for 2005...
INFO:__main__:Scraping WBB schedules for year 2006...
INFO:__main__:0.8036586205164592 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2006...
INFO:__main__:Finished WBB PBP for 2006...
INFO:__main__:Scraping WBB schedules for year 2007...
INFO:__main__:0.9698696851730346 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2007...
INFO:__main__:Finished WBB PBP for 2007...
INFO:__main__:Scraping WBB schedules for year 2008...
INFO:__main__:1.092712112267812 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2008...
INFO:__main__:Finished WBB PBP for 2008...
INFO:__main__:Scraping WBB schedules for year 2009...
INFO:__main__:0.9224404136339823 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2009...
INFO:__main__:Finished WBB PBP for 2009...
INFO:__main__:Scraping WBB schedules for year 2010...
INFO:__main__:0.9719517230987549 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2010...
INFO:__main__:Finished WBB PBP for 2010...
INFO:__main__:Scraping WBB schedules for year 2011...
INFO:__main__:1.0806501865386964 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2011...
INFO:__main__:Finished WBB PBP for 2011...
INFO:__main__:Scraping WBB schedules for year 2012...
INFO:__main__:1.0797465562820434 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2012...
INFO:__main__:Finished WBB PBP for 2012...
INFO:__main__:Scraping WBB schedules for year 2013...
INFO:__main__:1.075572919845581 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2013...
INFO:__main__:Finished WBB PBP for 2013...
INFO:__main__:Scraping WBB schedules for year 2014...
INFO:__main__:1.1394915938377381 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2014...
INFO:__main__:Finished WBB PBP for 2014...
INFO:__main__:Scraping WBB schedules for year 2015...
INFO:__main__:1.0632030685742697 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2015...
INFO:__main__:Finished WBB PBP for 2015...
INFO:__main__:Scraping WBB schedules for year 2016...
INFO:__main__:1.0355625391006469 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2016...
INFO:__main__:Finished WBB PBP for 2016...
INFO:__main__:Scraping WBB schedules for year 2017...
INFO:__main__:1.2369691014289856 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2017...
INFO:__main__:Finished WBB PBP for 2017...
INFO:__main__:Scraping WBB schedules for year 2018...
INFO:__main__:1.2277672171592713 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2018...
INFO:__main__:Finished WBB PBP for 2018...
INFO:__main__:Scraping WBB schedules for year 2019...
INFO:__main__:1.2201746185620626 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2019...
INFO:__main__:Finished WBB PBP for 2019...
INFO:__main__:Scraping WBB schedules for year 2020...
INFO:__main__:1.2657807111740111 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2020...
INFO:__main__:Finished WBB PBP for 2020...
INFO:__main__:Scraping WBB schedules for year 2021...
INFO:__main__:0.9230466961860657 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2021...
INFO:__main__:Finished WBB PBP for 2021...
INFO:__main__:Scraping WBB schedules for year 2022...
INFO:__main__:1.1482917984326682 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2022...
INFO:__main__:Finished WBB PBP for 2022...
INFO:__main__:Scraping WBB schedules for year 2023...
INFO:__main__:1.0983669678370158 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2023...
INFO:__main__:Finished WBB PBP for 2023...
INFO:__main__:Scraping WBB schedules for year 2004...
INFO:__main__:1.4537965536117554 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2004...
INFO:__main__:Number of Games: 4780
INFO:__main__:2.545599154631297 minutes to download 4780 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2004...
INFO:__main__:Scraping WBB schedules for year 2005...
INFO:__main__:1.4175319433212281 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2005...
INFO:__main__:Number of Games: 4856
ERROR:__main__:TypeError: game_id = 250510135
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 250510135
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/250510135.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/250510135.json'
INFO:__main__:2.6296774983406066 minutes to download 4856 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2005...
INFO:__main__:Scraping WBB schedules for year 2006...
INFO:__main__:1.4503452022870382 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2006...
INFO:__main__:Number of Games: 4873
ERROR:__main__:TypeError: game_id = 260430127
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 260430127
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/260430127.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/260430127.json'
INFO:__main__:2.9860249439875286 minutes to download 4873 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2006...
INFO:__main__:Scraping WBB schedules for year 2007...
INFO:__main__:1.505158015092214 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2007...
INFO:__main__:Number of Games: 5239
ERROR:__main__:TypeError: game_id = 270180275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270180275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270180275.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270180275.json'
ERROR:__main__:TypeError: game_id = 270250275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270250275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270250275.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270250275.json'
ERROR:__main__:TypeError: game_id = 270280275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270280275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270280275.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270280275.json'
ERROR:__main__:TypeError: game_id = 270350213
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270350213
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270350213.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270350213.json'
ERROR:__main__:TypeError: game_id = 270420275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270420275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270420275.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270420275.json'
ERROR:__main__:TypeError: game_id = 270460194
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270460194
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270460194.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270460194.json'
ERROR:__main__:TypeError: game_id = 270490275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270490275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270490275.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270490275.json'
ERROR:__main__:TypeError: game_id = 270600275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270600275
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270600275.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270600275.json'
ERROR:__main__:TypeError: game_id = 270902751
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 270902751
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270902751.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/270902751.json'
INFO:__main__:3.677456208070119 minutes to download 5239 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2007...
INFO:__main__:Scraping WBB schedules for year 2008...
INFO:__main__:1.5977100809415181 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2008...
INFO:__main__:Number of Games: 5341
ERROR:__main__:KeyError: game_id =  game_id = 273322870
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 280402542
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:7.951108626524607 minutes to download 5341 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2008...
INFO:__main__:Scraping WBB schedules for year 2009...
INFO:__main__:1.657823872566223 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2009...
INFO:__main__:Number of Games: 5430
ERROR:__main__:KeyError: game_id =  game_id = 283290233
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 290170435
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 96, in helper_wbb_pbp
    homeTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][0]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 96, in helper_wbb_pbp
    homeTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][0]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 290320233
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 290420164
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:6.430828134218852 minutes to download 5430 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2009...
INFO:__main__:Scraping WBB schedules for year 2010...
INFO:__main__:1.719402821858724 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2010...
INFO:__main__:Number of Games: 5450
ERROR:__main__:KeyError: game_id =  game_id = 293540233
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 293640349
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:5.640522650877634 minutes to download 5450 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2010...
INFO:__main__:Scraping WBB schedules for year 2011...
INFO:__main__:1.6621697306632996 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2011...
INFO:__main__:Number of Games: 5461
INFO:__main__:4.762175198396047 minutes to download 5461 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2011...
INFO:__main__:Scraping WBB schedules for year 2012...
INFO:__main__:1.6681986649831135 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2012...
INFO:__main__:Number of Games: 5463
ERROR:__main__:KeyError: game_id =  game_id = 313150301
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 313530082
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:7.587528312206269 minutes to download 5463 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2012...
INFO:__main__:Scraping WBB schedules for year 2013...
INFO:__main__:1.6995999813079834 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2013...
INFO:__main__:Number of Games: 5484
ERROR:__main__:KeyError: game_id =  game_id = 323150301
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 323490082
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 323652458
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:8.742297089099884 minutes to download 5484 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2013...
INFO:__main__:Scraping WBB schedules for year 2014...
INFO:__main__:1.9641568342844644 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2014...
INFO:__main__:Number of Games: 5588
ERROR:__main__:TypeError: game_id = 400505785
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400505785
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400505785.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400505785.json'
ERROR:__main__:TypeError: game_id = 400510532
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400510532
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400510532.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400510532.json'
ERROR:__main__:TypeError: game_id = 400512490
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400512490
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400512490.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400512490.json'
ERROR:__main__:TypeError: game_id = 400510576
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400510576
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400510576.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400510576.json'
ERROR:__main__:TypeError: game_id = 400508342
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400508342
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400508342.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400508342.json'
ERROR:__main__:TypeError: game_id = 400509780
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400509780
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400509780.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400509780.json'
ERROR:__main__:KeyError: game_id =  game_id = 400511776
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:TypeError: game_id = 400512545
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400512545
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400512545.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400512545.json'
ERROR:__main__:TypeError: game_id = 400541614
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400541614
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400541614.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400541614.json'
ERROR:__main__:TypeError: game_id = 400542295
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400542295
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400542295.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400542295.json'
ERROR:__main__:TypeError: game_id = 400543174
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400543174
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400543174.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400543174.json'
ERROR:__main__:TypeError: game_id = 400543734
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400543734
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400543734.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400543734.json'
ERROR:__main__:TypeError: game_id = 400544211
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400544211
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400544211.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400544211.json'
ERROR:__main__:TypeError: game_id = 400547098
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ERROR:__main__:FileNotFoundError: game_id = 400547098
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400547098.json'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 70, in download_game
    processed_data = sdv.wbb.wbb_pbp_disk(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 72, in wbb_pbp_disk
    with open(os.path.join(path_to_json, "{}.json".format(game_id))) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'wbb/json/raw/400547098.json'
INFO:__main__:7.762821829319 minutes to download 5588 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2014...
INFO:__main__:Scraping WBB schedules for year 2015...
INFO:__main__:1.7371946493784587 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2015...
INFO:__main__:Number of Games: 5603
ERROR:__main__:KeyError: game_id =  game_id = 400602757
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 400601732
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:8.529007844130199 minutes to download 5603 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2015...
INFO:__main__:Scraping WBB schedules for year 2016...
INFO:__main__:2.575418674945831 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2016...
INFO:__main__:Number of Games: 5619
ERROR:__main__:KeyError: game_id =  game_id = 400823550
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 400849312
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 96, in helper_wbb_pbp
    homeTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][0]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 96, in helper_wbb_pbp
    homeTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][0]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:8.89611363808314 minutes to download 5619 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2016...
INFO:__main__:Scraping WBB schedules for year 2017...
INFO:__main__:2.522260574499766 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2017...
INFO:__main__:Number of Games: 5622
INFO:__main__:9.655700556437175 minutes to download 5622 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2017...
INFO:__main__:Scraping WBB schedules for year 2018...
INFO:__main__:2.413267461458842 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2018...
INFO:__main__:Number of Games: 5630
ERROR:__main__:KeyError: game_id =  game_id = 400995293
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 400998249
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:9.14263511498769 minutes to download 5630 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2018...
INFO:__main__:Scraping WBB schedules for year 2019...
INFO:__main__:2.1599151372909544 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2019...
INFO:__main__:Number of Games: 5658
ERROR:__main__:KeyError: game_id =  game_id = 401097252
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:TypeError: game_id = 401093990
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 29, in espn_wbb_pbp
    summary = json.loads(summary_resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
INFO:__main__:9.170674792925517 minutes to download 5658 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2019...
INFO:__main__:Scraping WBB schedules for year 2020...
INFO:__main__:2.845194387435913 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2020...
INFO:__main__:Number of Games: 5434
ERROR:__main__:KeyError: game_id =  game_id = 401180676
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 401180016
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:21.591418385505676 minutes to download 5434 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2020...
INFO:__main__:Scraping WBB schedules for year 2021...
INFO:__main__:1.6230626662572225 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2021...
INFO:__main__:Number of Games: 3823
INFO:__main__:15.926668552557627 minutes to download 3823 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2021...
INFO:__main__:Scraping WBB schedules for year 2022...
INFO:__main__:2.2572176575660707 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2022...
INFO:__main__:Number of Games: 5534
INFO:__main__:23.654425179958345 minutes to download 5534 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2022...
INFO:__main__:Scraping WBB schedules for year 2023...
INFO:__main__:2.5849284052848818 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2023...
INFO:__main__:Number of Games: 5828
ERROR:__main__:KeyError: game_id =  game_id = 401487950
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 401481369
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 401493630
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 401486821
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
ERROR:__main__:KeyError: game_id =  game_id = 401493128
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 75, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 102, in helper_wbb_pbp
    awayTeamAbbrev = str(pbp_txt['header']['competitions'][0]['competitors'][1]['team']['abbreviation'])
KeyError: 'abbreviation'
INFO:__main__:24.69532820781072 minutes to download 5828 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2023...
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sports.core.api.espn.com:443
DEBUG:urllib3.connectionpool:https://sports.core.api.espn.com:443 "GET /v2/sports/basketball/leagues/womens-college-basketball/seasons/2024/types/2/calendar/ondays HTTP/1.1" 200 None
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.221566315491994 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 816
INFO:__main__:2.118130834897359 minutes to download 816 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0005258361498517 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 816
INFO:__main__:2.154426018397013 minutes to download 816 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.2196598291397094 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 816
INFO:__main__:2.116053549448649 minutes to download 816 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.202936255931854 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 848
INFO:__main__:2.083168884118398 minutes to download 848 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.36785888671875 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 891
INFO:__main__:2.1423123637835184 minutes to download 891 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.342811365922292 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 916
ERROR:__main__:TypeError: game_id = 401598260
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401595087
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:2.238299230734507 minutes to download 916 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.1921932895978293 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 999
INFO:__main__:2.421377913157145 minutes to download 999 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.258513394991557 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1094
INFO:__main__:2.6441094438234964 minutes to download 1094 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.238797867298126 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1148
INFO:__main__:2.9217729727427164 minutes to download 1148 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.3055286447207135 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1161
INFO:__main__:2.9409164150555926 minutes to download 1161 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.043590219815572 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1187
INFO:__main__:2.814584465821584 minutes to download 1187 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0422103961308795 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1264
INFO:__main__:2.982177698612213 minutes to download 1264 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0292823910713196 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1303
INFO:__main__:3.1282944043477374 minutes to download 1303 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.8995928724606832 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1328
ERROR:__main__:TypeError: game_id = 401608801
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401583949
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:3.0410463412602744 minutes to download 1328 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9383679986000062 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1393
INFO:__main__:2.995422359307607 minutes to download 1393 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9812756617863974 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1459
INFO:__main__:3.239352901776632 minutes to download 1459 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9701443513234456 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1474
INFO:__main__:3.220175258318583 minutes to download 1474 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.920549484093984 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1510
INFO:__main__:3.3552247802416484 minutes to download 1510 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.032888122399648 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1570
INFO:__main__:3.5093381881713865 minutes to download 1570 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9840469042460123 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1594
INFO:__main__:3.587026913960775 minutes to download 1594 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9719288070996603 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1608
INFO:__main__:3.5203726728757223 minutes to download 1608 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.20293748776118 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1666
INFO:__main__:3.6859280745188396 minutes to download 1666 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9797581831614177 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1735
INFO:__main__:3.8690343578656514 minutes to download 1735 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9576124747594197 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1753
INFO:__main__:3.9200245420138042 minutes to download 1753 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.8886563420295714 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1770
INFO:__main__:3.864782937367757 minutes to download 1770 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.014923290411631 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1788
INFO:__main__:3.975053000450134 minutes to download 1788 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9426746686299643 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1814
INFO:__main__:4.005665457248687 minutes to download 1814 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9198164661725363 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1833
INFO:__main__:3.9466065883636476 minutes to download 1833 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9736137668291727 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1890
INFO:__main__:4.127792298793793 minutes to download 1890 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.2222461740175885 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1943
INFO:__main__:4.235278181234995 minutes to download 1943 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.108955530325572 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 1984
INFO:__main__:4.324673223495483 minutes to download 1984 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9418020645777385 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2015
INFO:__main__:4.414212576548258 minutes to download 2015 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0222612102826436 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2096
ERROR:__main__:Exception: game_id = 401601207
 Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 20, in download
    response = session.get(url, params=params, proxies=proxy, headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 35, in espn_wbb_pbp
    summary_resp = download(summary_url, **kwargs)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 31, in download
    logger.warning("%s: %i - %s for url (%s)", e, response.status_code, response.reason, response.url)
UnboundLocalError: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 20, in download
    response = session.get(url, params=params, proxies=proxy, headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 35, in espn_wbb_pbp
    summary_resp = download(summary_url, **kwargs)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 31, in download
    logger.warning("%s: %i - %s for url (%s)", e, response.status_code, response.reason, response.url)
UnboundLocalError: local variable 'response' referenced before assignment
INFO:__main__:4.828127443790436 minutes to download 2096 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9337959011395773 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2183
INFO:__main__:4.8655489404996235 minutes to download 2183 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9273747563362122 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2199
INFO:__main__:4.781306298573812 minutes to download 2199 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.929117993513743 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2199
INFO:__main__:4.81195361216863 minutes to download 2199 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9724242568016053 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2199
INFO:__main__:4.8325011968612674 minutes to download 2199 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9600487271944682 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2199
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187)
ERROR:sdv.dl_utils:Retry Limit Exceeded: http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187 
params: {}
 NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187
ERROR:sdv.dl_utils:Download Error: http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187 
params: {}
 NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401588187
ERROR:__main__:TypeError: game_id = 401588187
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:4.9312189300855005 minutes to download 2199 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9927348375320435 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2200
ERROR:__main__:TypeError: game_id = 401608761
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401576981
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401594964
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:5.2519606669743855 minutes to download 2200 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0071428616841636 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2202
INFO:__main__:5.121281413237254 minutes to download 2202 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9697413841883342 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2221
INFO:__main__:5.002519432703654 minutes to download 2221 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0088037490844726 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2251
INFO:__main__:4.991351707776388 minutes to download 2251 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9644002874692281 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2356
ERROR:__main__:TypeError: game_id = 401598325
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401598241
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401598300
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401599297
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401604594
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:5.2771369616190595 minutes to download 2356 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.928849184513092 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2400
INFO:__main__:5.3565791289011635 minutes to download 2400 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9680104851722717 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2406
INFO:__main__:5.485435167948405 minutes to download 2406 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.9523838758468628 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2417
INFO:__main__:5.603947750727335 minutes to download 2417 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:1.940288237730662 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2471
INFO:__main__:5.45861253341039 minutes to download 2471 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.021644941965739 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2539
INFO:__main__:5.909567431608836 minutes to download 2539 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.025278846422831 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2557
INFO:__main__:6.13031302690506 minutes to download 2557 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0194900751113893 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2680
INFO:__main__:6.259510143597921 minutes to download 2680 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.024392819404602 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2723
INFO:__main__:6.524099055926005 minutes to download 2723 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.0949808438618978 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2735
ERROR:__main__:Exception: game_id = 401589517
 Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 20, in download
    response = session.get(url, params=params, proxies=proxy, headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 35, in espn_wbb_pbp
    summary_resp = download(summary_url, **kwargs)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 31, in download
    logger.warning("%s: %i - %s for url (%s)", e, response.status_code, response.reason, response.url)
UnboundLocalError: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 20, in download
    response = session.get(url, params=params, proxies=proxy, headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 35, in espn_wbb_pbp
    summary_resp = download(summary_url, **kwargs)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 31, in download
    logger.warning("%s: %i - %s for url (%s)", e, response.status_code, response.reason, response.url)
UnboundLocalError: local variable 'response' referenced before assignment
ERROR:__main__:Exception: game_id = 401584599
 Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 20, in download
    response = session.get(url, params=params, proxies=proxy, headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 35, in espn_wbb_pbp
    summary_resp = download(summary_url, **kwargs)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 31, in download
    logger.warning("%s: %i - %s for url (%s)", e, response.status_code, response.reason, response.url)
UnboundLocalError: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 20, in download
    response = session.get(url, params=params, proxies=proxy, headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='site.api.espn.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 50, in download_game
    g = sdv.wbb.espn_wbb_pbp(game_id = game, raw = True)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 35, in espn_wbb_pbp
    summary_resp = download(summary_url, **kwargs)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/dl_utils.py", line 31, in download
    logger.warning("%s: %i - %s for url (%s)", e, response.status_code, response.reason, response.url)
UnboundLocalError: local variable 'response' referenced before assignment
INFO:__main__:6.679972755908966 minutes to download 2735 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.081888250509898 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2741
INFO:__main__:6.80674246152242 minutes to download 2741 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.1730112791061402 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2793
INFO:__main__:6.73114341100057 minutes to download 2793 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.1243241310119627 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2871
INFO:__main__:6.9150513172149655 minutes to download 2871 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.2599208394686383 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 2864
ERROR:__main__:TypeError: game_id = 401598244
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401601153
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401594667
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401595052
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401583957
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401603820
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401604853
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401594833
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401582203
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401588180
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401610061
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401598983
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401594904
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
ERROR:__main__:TypeError: game_id = 401598411
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:6.847824283440908 minutes to download 2864 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.14081830183665 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3001
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
WARNING:sdv.dl_utils:NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406: 404 - Not Found for url (http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406)
ERROR:sdv.dl_utils:Retry Limit Exceeded: http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406 
params: {}
 NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406
ERROR:sdv.dl_utils:Download Error: http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406 
params: {}
 NoESPNDataError: No response for http://site.api.espn.com/apis/site/v2/sports/basketball/womens-college-basketball/summary?event=401582406
ERROR:__main__:TypeError: game_id = 401582406
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 101, in helper_wbb_pbp
    pbp_txt, init = helper_wbb_game_data(pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 139, in helper_wbb_game_data
    pbp_txt["teamInfo"] = pbp_txt["header"]["competitions"][0]
TypeError: list indices must be integers or slices, not str
INFO:__main__:7.085907781124115 minutes to download 3001 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.300481677055359 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3049
INFO:__main__:7.41892583767573 minutes to download 3049 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.149954688549042 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3064
INFO:__main__:7.2890688419342045 minutes to download 3064 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.284397312005361 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3069
INFO:__main__:7.462024545669555 minutes to download 3069 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.1667688727378844 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3116
ERROR:__main__:Exception: game_id = 401603311
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
ERROR:__main__:Exception: game_id = 401603314
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
INFO:__main__:7.527334221204122 minutes to download 3116 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.1886348088582355 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3185
ERROR:__main__:Exception: game_id = 401603311
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
ERROR:__main__:Exception: game_id = 401603314
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
INFO:__main__:7.43447292248408 minutes to download 3185 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
INFO:__main__:Scraping WBB schedules for year 2024...
INFO:__main__:2.119897731145223 minutes to download 1 years of season schedules.
INFO:__main__:Scraping WBB PBP for 2024...
INFO:__main__:Number of Games: 3207
ERROR:__main__:Exception: game_id = 401603311
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
ERROR:__main__:Exception: game_id = 401603314
 Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
Traceback (most recent call last):
  File "python/scrape_wbb_json.py", line 78, in download_game
    result = sdv.wbb.helper_wbb_pbp(
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 104, in helper_wbb_pbp
    pbp_txt = helper_wbb_pbp_features(game_id, pbp_txt, init)
  File "/mnt/sdv_repos/sdv-py/sportsdataverse/wbb/wbb_pbp.py", line 231, in helper_wbb_pbp_features
    pbp_txt["plays"]
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/frame.py", line 7631, in with_columns
    self.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
exceptions.ColumnNotFoundError: id

Error originated just after this operation:
DF []; PROJECT */0 COLUMNS; SELECTION: "None"
INFO:__main__:7.392259748776754 minutes to download 3207 game play-by-plays.
INFO:__main__:Finished WBB PBP for 2024...
